filter:
    excluded_paths:
        - "tests/"
        - "resources/"
        - "vendor/"

build:
    environment:
        php: 7.1.3
        mysql: true
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
